Prevent message `NoSuchMethodError: The method 'markNeedsBuild' was called on null.` when setState is called in _showAndDelayHide after IncidentPage is disposed and removed from the widget tree.